favicon: null
name: Zack Smith
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5143369
  brandStrength: 0.5563407035078853
  lightness: 0.5071685
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  rhythmicContrast: 0.5089605
typography_spectrum: 0.874552
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3476703
analytics:
  twitter: null
  google: null
  facebook: null
