name: Zack Smith
favicon: null
layout_spectrum: 0.22523259930312634
typography_spectrum: 0.6952076766174287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5563407035078853
  lightness: 0.11149852350354195
  saturation: 0.5210228585638106
  rhythmicContrast: 0.47154076397418976
purpose: []
